UI/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using BLL;


namespace UI.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        UserBLL userbll = new UserBLL();
        // GET: Admin/Login
        public ActionResult Index()
        {
            UserDTO dto = new UserDTO();
            return View(dto);
        }
        [HttpPost]
        public ActionResult Index(UserDTO model)
        {
            /*var errors = ModelState
    .Where(x => x.Value.Errors.Count > 0)
    .Select(x => new { x.Key, x.Value.Errors })
    .ToArray();*/
            if (!ModelState.IsValid)
            {
                //return model.RequiredAttribute();
                UserDTO user = userbll.GetUserWithUsernameAndPassword(model);
                if (user.ID != 0)
                {
                    UserStatic.UserID = user.ID;
                    UserStatic.isAdmin = user.IsAdmin;
                    UserStatic.NameSurname = user.Name;
                    UserStatic.ImagePath = user.ImagePath;
                    LogBLL.AddLog(General.ProcessType.Login,General.TableName.Login, 12);
                    return RedirectToAction("Index", "Post");

                }
                else
                //Console.WriteLine(errors);
                return View(model);   
            }
            else
                return View(model);
        }

    }
}

UI/Areas/Admin/Controllers/MetaController.cs
using BLL;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class MetaController : Controller
    {
        // GET: Admin/Meta
        public ActionResult Index()
        {
            return View();
        }
        MetaBLL bll = new MetaBLL();
        public ActionResult AddMeta()
        {
            MetaDTO dto = new MetaDTO();
            return View(dto);
        }
        [HttpPost]
        public ActionResult AddMeta(MetaDTO model)
        {
            if (ModelState.IsValid)
            {
                if (bll.AddMeta(model))
                {
                    ViewBag.ProcessState = General.Messages.AddSuccess;
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.ProcessState = General.Messages.GeneralError;
                }
            }
            else
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }
            MetaDTO newmodel = new MetaDTO();
            return View(newmodel);

        }
        public ActionResult MetaList()
        {
            List<MetaDTO> model = new List<MetaDTO>();
            model = bll.GetMetaData();
            return View(model);
        }
        public ActionResult UpdateMeta(int ID)
        {
            MetaDTO model = new MetaDTO();
            model = bll.GetMetaWithID(ID);
            return View(model);
        }
        [HttpPost]
        public ActionResult UpdateMeta(MetaDTO model)
        {
            if (ModelState.IsValid)
            {
                if (bll.UpdateMeta(model))
                {
                    ViewBag.ProcessState = General.Messages.UpdateSuccess;
                }
                else
                {
                    ViewBag.ProcessState = General.Messages.GeneralError;
                }
            }
            else
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        // GET: Admin/Post
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI/Areas/Admin/Controllers/SocialMediaController.cs
using BLL;
using DTO;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class SocialMediaController : Controller
    {

        SocialMediaBLL bll = new SocialMediaBLL();
        // GET: Admin/SocialMedia
        public ActionResult AddSocialMedia()
        {
            SocialMediaDTO model = new SocialMediaDTO();
            return View(model);
        }
        [HttpPost]
        public ActionResult AddSocialMedia(SocialMediaDTO model)
        {
            if (model.SocialImage == null)
            {
                ViewBag.ProcessState = General.Messages.ImageMissing;
                
            }
            else if (!ModelState.IsValid)
            {
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        
                    }
                }
                string filename = "";
                HttpPostedFileBase postedfile = model.SocialImage;
                Bitmap SocialMedia = new Bitmap(postedfile.InputStream);
                string ext = Path.GetExtension(postedfile.FileName);
                    //Path.GetExtension(postedfile.FileName);
               
                if(ext == ".jpg" || ext == ".jpeg" || ext==".png"|| ext == ".gif")
                {
                    string uniquenumber = Guid.NewGuid().ToString();
                    filename = uniquenumber + postedfile.FileName;
                    SocialMedia.Save(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" + filename));
                    model.ImagePath = filename;
                    if (bll.AddSocialMedia(model))
                    {
                        ViewBag.ProcessState = General.Messages.AddSuccess;
                        model = new SocialMediaDTO();
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.ProcessState = General.Messages.GeneralError;
                    }
                }
                else
                {
                    ViewBag.ProcessState = General.Messages.ExtensionError;
                }

            }
            else
            {
                ViewBag.Process.State = General.Messages.EmptyArea;
            }
            SocialMediaDTO model2 = new SocialMediaDTO();
            return View(model2);
        }

        public ActionResult SocialMediaList()
        {
            List<SocialMediaDTO> dtolist = new List<SocialMediaDTO>();
            dtolist = bll.GetSocialMedias();
            return View(dtolist);
        }
        public ActionResult UpdateSocialMedia(int ID)
        {
            SocialMediaDTO dto = bll.GetSocialMediaWithID(ID);
            return View(dto);
        }
        [HttpPost]
        public ActionResult UpdateSocialMedia(SocialMediaDTO model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }
            else
            {
                if (model.SocialImage != null)
                {
                    
                    HttpPostedFileBase postedfile = model.SocialImage;
                    Bitmap SocialMedia = new Bitmap(postedfile.InputStream);
                    string ext = Path.GetExtension(postedfile.FileName);
                    //Path.GetExtension(postedfile.FileName);
                    string filename = "";

                    if (ext == ".jpg" || ext == ".jpeg" || ext == ".png" || ext == ".gif")
                    {
                        string uniquenumber = Guid.NewGuid().ToString();
                        filename = uniquenumber + postedfile.FileName;
                        SocialMedia.Save(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" + filename));
                        model.ImagePath = filename;
                    }

                }//delete
                string oldImagePath = bll.UpdateSocialMedia(model);
                if (model.SocialImage != null)
                {
                    if (System.IO.File.Exists(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/"+ oldImagePath)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/Areas/Admin/Content/SocialMediaImages/" + oldImagePath));
                    }
                }
                ViewBag.ProcessState = General.Messages.UpdateSuccess;
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    
}

@model DTO.UserDTO 

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Doga's' | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link href="~/Areas/Admin/Content/CSS/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->

    <link href="~/Areas/Admin/Content/CSS/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    
    <link href="~/Areas/Admin/Content/CSS/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Doga's'</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Username" name="Username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Username)
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" name="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Password)
                    <div class="row">

                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                
                <!-- /.social-auth-links -->

                
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->

    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <!-- Bootstrap 4 -->

    <script src="~/Areas/Admin/Content/JS/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    
    <script src="~/Areas/Admin/Content/JS/adminlte.min.js"></script>

</body>
</html>

UI/Areas/Admin/Views/Meta/AddMeta.cshtml
@{
    ViewBag.Title = "AddMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<section class="content-headr">

    <h1>Add Meta operation</h1>
    <ol class=" breadcrumb" float-sm-left>
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Add Meta</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary"href="/Admin/Meta/MetaList">Meta List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using(Html.BeginForm("AddMeta","Meta",FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.Partial("Partial/MetaForm")
            }

            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Meta/MetaList.cshtml
@{
    ViewBag.Title = "MetaList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
@model List<DTO.MetaDTO>

<section class="content-headr">

    <h1>Meta List</h1>
    <ol class=" breadcrumb" float-sm-left>
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Meta List</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" href="/Admin/Meta/AddMeta">Add Meta</button>
</div>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Meta Content</th>
                    <th>Update</th>
                    <th>Delete</th>

                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tbody>
                    <tr id="a_@item.MetaID">
                        <td>@item.Name</td>
                        <td>
                            @item.MetaContent
                        </td>
                        <!--FOR UPDATE-->
                        <td align="center" valign="middle">
                            <a href="/Admin/Meta/UpdateMeta/@item.MetaID">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/update1.png"
                            </a>
                        </td>
                        <!--FOR DELETE-->
                        <td align="center" valign="middle">
                            <a href="#">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/delete1.png"
                            </a>
                        </td>
                        
                    </tr>

                </tbody>
            }

            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Meta Content</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

UI/Areas/Admin/Views/Meta/Partial/MetaForm.cshtml
@model DTO.MetaDTO
<div class="box-body">
    <div class="form-group">
        <label> Meta Content</label>
        @Html.TextBoxFor(x => x.MetaContent, new {@class = "form-control",@placeholder = "Meta Content"})
        @Html.ValidationMessageFor(x => x.MetaContent)
        </div>
        <div class="form-group">
                <label> Name</label>
                @Html.DropDownList("Name", new SelectList(new[] {"Keywords","Description","Author","Twittercard"}), new {@class = "form-control select2"})
        </div>
        <input type="number" name ="MetaID" value="@Model.MetaID" hidden/>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    


</div>

UI/Areas/Admin/Views/Meta/UpdateMeta.cshtml
@{
    ViewBag.Title = "UpdateMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-headr">

    <h1>Update Meta operation</h1>
    <ol class=" breadcrumb" float-sm-left>
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Update Meta</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" href="/Admin/Meta/MetaList">Metal List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("UpdateMeta", "Meta", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/MetaForm")
                }

            </div>
        </div>
    </div>
</section>
<h2>AddMeta</h2>

UI/Areas/Admin/Views/Post/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

UI/Areas/Admin/Views/Shared/MessageForm.cshtml
@using UI.Areas.Admin;

@if (ViewBag.ProcessState == BLL.General.Messages.AddSuccess)
{
    <div class="alert alert-success">
        <strong>Success! Add Operation was completed Successfully</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.EmptyArea)
{
    <div class="alert alert-danger">
        <strong>Error! Please  fill the necessary area</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.UpdateSuccess)
{
    <div class="alert alert-danger">
        <strong>Success! Update Operation has been successfull</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.ImageMissing)
{
    <div class="alert alert-danger">
        <strong>Error! Please select an image</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.ExtensionError)
{
    <div class="alert alert-danger">
        <strong>Error! Please select files with true extensions</strong>
    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.GeneralError)
{
    <div class="alert alert-danger">
        <strong>Error!</strong>
    </div>
}

UI/Areas/Admin/Views/SocialMedia/AddSocialMedia.cshtml
@{
    ViewBag.Title = "AddSocialMedia";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-headr">

    <h1>Add Social Media</h1>
    <ol class=" breadcrumb" float-sm-left>
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Add Social Media</a></li>
        <li class="breadcrumb-item active"><a>Add Social Media</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary"  onclick="window.location.href='/Admin/SocialMedia/SocialMediaList'">Social Media List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddSocialMedia", "SocialMedia", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/SocialMediaForm")
                }

            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/SocialMedia/Partial/SocialMediaForm.cshtml
@model DTO.SocialMediaDTO
    <div class = "box-body">
     <div class="form-group">
         <label>Name</label>
         @Html.TextBoxFor(x=>x.Name, new { @class= "form-control", @placeholder = "Social Media Name"})
         @Html.ValidationMessageFor(x=>x.Name)

     </div>   
        <div class="form-group">
            <label>Link</label>
            @Html.TextBoxFor(x=>x.Link, new {@class = "form-control", @placeholder = "Social Media Link"})
            @Html.ValidationMessageFor(x=>x.Link)

        </div>
        <input hidden type="number" value=" = @Model.ID" name="ID"/>
        <div class="form-group">
            @Html.LabelFor(x => x.SocialImage)
            <input type="file" name="SocialImage" accept="image/gif, image/jpeg, image/png, image/jpg" 
                   onchange="$('#SocialImage')[0].src = window.URL.createObjectURL(this.files[0]" />
            <br />
            @if (Model != null && Model.ImagePath != null)
            {
                <br />
                <img src="~/Areas/Admin/Content/SocialMediaImages/@Model.ImagePath" width="300" height="200"/>
            }
            else
            {
                <img src="" width="300" height="200" id="SocialImage"/>
            }

        </div>
        <div class="card-footer">
            <button class="btn btn-primary">Save</button>
        </div>
    </div>

UI/Areas/Admin/Views/SocialMedia/SocialMediaList.cshtml
@{
    ViewBag.Title = "SocialMediaList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model List<DTO.SocialMediaDTO>

<section class="content-headr">

    <h1>Meta List</h1>
    <ol class=" breadcrumb" float-sm-left>
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Social Media</a></li>
        <li class="breadcrumb-item active"><a>Social Media List</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/SocialMedia/AddSocialMedia'" >Add Social Media</button>
</div>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Link</th>
                    <th>Image</th>
                    <th>Update</th>
                    <th>Delete</th>

                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tbody>
                    <tr id="a_@item.ID">
                        <td>@item.Name</td>
                        <td>
                            @item.Link
                        </td>
                        <td>
                            <img src="~/Areas/Admin/Content/SocialMediaImages/@item.ImagePath" width="60" height="40" />


                        </td>
                        <!--FOR UPDATE-->
                        <td align="center" valign="middle">
                            <a href="/Areas/Admin/SocialMedia/UpdateSocialMedia/@item.ID">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/update1.png" />
                            </a>
                        </td>
                        <!--FOR DELETE-->
                        <td align="center" valign="middle">
                            <a href="#">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/delete1.png" />
                            </a>
                        </td>

                    </tr>

                </tbody>
            }

            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Meta Content</th>
                    <th>Image</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

UI/Areas/Admin/Views/SocialMedia/UpdateSocialMedia.cshtml
@{
    ViewBag.Title = "UpdateSocialMedia";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-headr">

    <h1>Update Social Media</h1>
    <ol class=" breadcrumb" float-sm-left>
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Social Media</a></li>
        <li class="breadcrumb-item active"><a>Update Social Media</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='~/Admin/SocialMedia/SocialMediaList'">Social Media List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("UpdateSocialMedia", "SocialMedia", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/SocialMediaForm")
                }

            </div>
        </div>
    </div>
</section>